version: "3.1"

services:
  Cafe-Runtime:
    image: phheetty/Cafe-uat:v.1.0.0
    ports:
      - "3515:3515"
    networks:
      - my-attachable-overlay-network
    # volumes:
    #   - ./:/code
    restart: always

networks:
  my-attachable-overlay-network:
    external: true


    